spring:
  application:
    name: KBT-comunity
  config:
    import: optional:application-secret.yml
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /v3/api-docs
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.actuate: DEBUG

