spring:
  application:
    name: KBT-comunity
  config:
    import: optional:application-secret.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.actuate: DEBUG

